-- Create coach_insights table for storing AI coaching results
CREATE TABLE coach_insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  trading_identity JSONB,
  core_edges JSONB,
  strengths JSONB,
  weaknesses JSONB,
  conditions JSONB,
  next_focus TEXT
);

-- Create index for faster user lookups
CREATE INDEX idx_coach_insights_user_id ON coach_insights(user_id);

-- Comment on the table and columns
COMMENT ON TABLE coach_insights IS 'Stores AI-generated trading coaching insights for users';
COMMENT ON COLUMN coach_insights.trading_identity IS 'Trader identity description with supporting evidence';
COMMENT ON COLUMN coach_insights.core_edges IS 'Array of core trading edges with statistics';
COMMENT ON COLUMN coach_insights.strengths IS 'Array of biggest strengths with evidence';
COMMENT ON COLUMN coach_insights.weaknesses IS 'Array of biggest weaknesses with evidence and recommendations';
COMMENT ON COLUMN coach_insights.conditions IS 'Conditions to seek and avoid with supporting statistics';
COMMENT ON COLUMN coach_insights.next_focus IS 'Single most impactful improvement opportunity';