-- Create pre_trade_commitments table for tracking trade commitments before execution
CREATE TABLE pre_trade_commitments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trade_id UUID REFERENCES trades(id) ON DELETE SET NULL,
  screenshot_url TEXT,
  thesis TEXT NOT NULL,
  setup_type TEXT NOT NULL,
  expected_outcome TEXT NOT NULL,
  invalidation_reason TEXT NOT NULL,
  confidence_score INTEGER NOT NULL CHECK (confidence_score BETWEEN 1 AND 10),
  selected_rules JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  locked_at TIMESTAMPTZ,
  is_locked BOOLEAN NOT NULL DEFAULT false,
  -- Additional metadata for analysis
  ticker TEXT,
  market_cap NUMERIC,
  float_shares NUMERIC,
  sector TEXT,
  relative_volume NUMERIC,
  avg_volume NUMERIC,
  day_volume NUMERIC
);

-- Create index for faster user lookups
CREATE INDEX idx_pre_trade_commitments_user_id ON pre_trade_commitments(user_id);

-- Create index for trade lookups
CREATE INDEX idx_pre_trade_commitments_trade_id ON pre_trade_commitments(trade_id);

-- Create index for setup type analysis
CREATE INDEX idx_pre_trade_commitments_setup_type ON pre_trade_commitments(setup_type);

-- Create index for ticker analysis
CREATE INDEX idx_pre_trade_commitments_ticker ON pre_trade_commitments(ticker);

-- Comment on the table and columns
COMMENT ON TABLE pre_trade_commitments IS 'Stores pre-trade commitments to enable accountability and process analysis';
COMMENT ON COLUMN pre_trade_commitments.thesis IS 'The trader''s stated reason for taking the trade';
COMMENT ON COLUMN pre_trade_commitments.setup_type IS 'The type of trade setup (e.g., breakout, pullback, momentum)';
COMMENT ON COLUMN pre_trade_commitments.expected_outcome IS 'What the trader expects to happen for the trade to work';
COMMENT ON COLUMN pre_trade_commitments.invalidation_reason IS 'Where the trader will exit if the trade idea is wrong';
COMMENT ON COLUMN pre_trade_commitments.confidence_score IS 'Trader''s confidence level (1-10) in the setup';
COMMENT ON COLUMN pre_trade_commitments.selected_rules IS 'Which of the trader''s rules this trade satisfies';
COMMENT ON COLUMN pre_trade_commitments.locked_at IS 'When the commitment was locked (before trade execution)';
COMMENT ON COLUMN pre_trade_commitments.is_locked IS 'Whether the commitment is locked and cannot be edited';