-- Create trade_pattern_analysis table for storing AI-generated trade pattern insights
CREATE TABLE trade_pattern_analysis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trade_id UUID NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
  commitment_id BIGINT REFERENCES pre_trade_commitments(id) ON DELETE SET NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  similar_trade_ids UUID[] NOT NULL DEFAULT '{}',
  similarity_scores JSONB NOT NULL DEFAULT '[]',
  matching_factors TEXT[] NOT NULL DEFAULT '{}',
  differing_factors TEXT[] NOT NULL DEFAULT '{}',
  setup_alignment_score INTEGER CHECK (setup_alignment_score BETWEEN 0 AND 100),
  rule_alignment_score INTEGER CHECK (rule_alignment_score BETWEEN 0 AND 100),
  historical_similarity_score INTEGER CHECK (historical_similarity_score BETWEEN 0 AND 100),
  ai_summary TEXT,
  ai_insights JSONB NOT NULL DEFAULT '{}',
  winning_pattern_matches INTEGER DEFAULT 0,
  losing_pattern_matches INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster trade lookups
CREATE INDEX idx_trade_pattern_analysis_trade_id ON trade_pattern_analysis(trade_id);

-- Create index for faster user lookups
CREATE INDEX idx_trade_pattern_analysis_user_id ON trade_pattern_analysis(user_id);

-- Create index for commitment lookups
CREATE INDEX idx_trade_pattern_analysis_commitment_id ON trade_pattern_analysis(commitment_id);

-- Create a function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_trade_pattern_analysis_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to update updated_at on changes
CREATE TRIGGER update_trade_pattern_analysis_updated_at
BEFORE UPDATE ON trade_pattern_analysis
FOR EACH ROW
EXECUTE FUNCTION update_trade_pattern_analysis_updated_at();

-- Comment on the table and columns
COMMENT ON TABLE trade_pattern_analysis IS 'Stores AI-generated insights comparing pre-trade commitments with actual execution';
COMMENT ON COLUMN trade_pattern_analysis.similar_trade_ids IS 'Array of similar trade IDs from user''s history';
COMMENT ON COLUMN trade_pattern_analysis.similarity_scores IS 'Similarity scores for each similar trade';
COMMENT ON COLUMN trade_pattern_analysis.matching_factors IS 'Factors that match the trader''s historical winning trades';
COMMENT ON COLUMN trade_pattern_analysis.differing_factors IS 'Factors that differ from the trader''s historical winning trades';
COMMENT ON COLUMN trade_pattern_analysis.setup_alignment_score IS 'How well the actual trade matched the pre-trade commitment (0-100)';
COMMENT ON COLUMN trade_pattern_analysis.rule_alignment_score IS 'How well the trade followed the trader''s stated rules (0-100)';
COMMENT ON COLUMN trade_pattern_analysis.historical_similarity_score IS 'How similar this trade is to the trader''s historical patterns (0-100)';
COMMENT ON COLUMN trade_pattern_analysis.ai_summary IS 'AI-generated summary of the trade analysis';
COMMENT ON COLUMN trade_pattern_analysis.ai_insights IS 'Structured AI insights about the trade';
COMMENT ON COLUMN trade_pattern_analysis.winning_pattern_matches IS 'Number of matches with the trader''s winning patterns';
COMMENT ON COLUMN trade_pattern_analysis.losing_pattern_matches IS 'Number of matches with the trader''s losing patterns';