-- Create trader_profiles table for persistent AI coaching memory
CREATE TABLE trader_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trading_style TEXT,
  preferred_setups TEXT[],
  risk_profile TEXT,
  strengths TEXT[],
  recurring_mistakes TEXT[],
  behavioral_patterns TEXT[],
  current_focus_area TEXT,
  coaching_notes TEXT,
  total_trades_analyzed INTEGER DEFAULT 0,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster user lookups
CREATE INDEX idx_trader_profiles_user_id ON trader_profiles(user_id);

-- Create a function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_trader_profiles_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.last_updated = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to update last_updated on profile changes
CREATE TRIGGER update_trader_profiles_updated_at
BEFORE UPDATE ON trader_profiles
FOR EACH ROW
EXECUTE FUNCTION update_trader_profiles_updated_at_column();

-- Comment on the table and columns
COMMENT ON TABLE trader_profiles IS 'Stores persistent trader profiles for AI coaching memory and personalization';
COMMENT ON COLUMN trader_profiles.trading_style IS 'Overall trading style (e.g., "Day trader focusing on low float momentum")';
COMMENT ON COLUMN trader_profiles.preferred_setups IS 'Array of preferred trading setups';
COMMENT ON COLUMN trader_profiles.risk_profile IS 'Risk tolerance and management style';
COMMENT ON COLUMN trader_profiles.strengths IS 'Array of identified trading strengths';
COMMENT ON COLUMN trader_profiles.recurring_mistakes IS 'Array of recurring mistakes and behavioral issues';
COMMENT ON COLUMN trader_profiles.behavioral_patterns IS 'Array of observed behavioral patterns';
COMMENT ON COLUMN trader_profiles.current_focus_area IS 'Current area of focus for improvement';
COMMENT ON COLUMN trader_profiles.coaching_notes IS 'Detailed coaching notes and observations';
COMMENT ON COLUMN trader_profiles.total_trades_analyzed IS 'Total number of trades analyzed for this profile';
COMMENT ON COLUMN trader_profiles.last_updated IS 'When the profile was last updated';
COMMENT ON COLUMN trader_profiles.created_at IS 'When the profile was created';